### PR TITLE
Invalidate cached value for elements after write

### PR DESCRIPTION
**Pull request by Joshpolansky**
# What 

Invalidate the data-machine-value on an element after the PLC value was written

# Why

We cache the previous PLC value in the HMI updates to avoid re-rendering values that haven't changed. When you write a value down to the PLC we weren't modifying that value. In most cases this was fine, because the value is changed, the element detects the change after a read and the element updates itself. 

The problem occurs when you write a value to the plc, and the PLC caps the value. So for example:

normal: 
|  state  | html  | previous value  | PLC |
|---|---|---| -- |
| start  | 200  | 200  |  200 |   
|  edit | 300  | 200  |   200 |  
|  write| 300  | 200  |   300 |  
|  read | 300  | 200  |  300 |

Limiting
|  state  | html  | previous value  | PLC |
|---|---|---| -- |
| start  | 200  | 200  |  200 |   
|  edit | 300  | 200  |   200 |  
|  write| 300  | 200  |   200 |  
|  read | 300  | 200  |  200 |

### CODE REVIEW

**Review by sclaiborne — COMMENTED** [review]
To clarify, does this introduce value "bounce"

| Before Change | Edit | HMI updates | HMI updates |
| --- | --- | --- | --- |
| 200 | 300 | 200 | 300 |

edit:

state | html | previous value | PLC
-- | -- | -- | --
start | 200 | 200 | 200
edit | 300 | 200 | 200
write | 300 | - | 300
update hmi  | 200 | 200 | 300
read | 300 | 300 | 300

**Comment by sclaiborne** [comment]
You could update the value on machine as well when you do a write

**Comment by Joshpolansky** [comment]
I think we are saying the same thing
instead of:
```javascript
  change: function (event) {
    var $this = $(this);
    var localMachine = window[WEBHMI.getMachineName($this)];
    localMachine.writeVariable(WEBHMI.getVarName($this), $this.val());
    localMachine.readVariable(WEBHMI.getVarName($this));
    $this.removeAttr('data-machine-value');
    }
```
->
```javascript
  change: function (event) {
    var $this = $(this);
    var localMachine = window[WEBHMI.getMachineName($this)];
    localMachine.writeVariable(WEBHMI.getVarName($this), $this.val());
    localMachine.readVariable(WEBHMI.getVarName($this));
    $this.attr('data-machine-value-num', varValue)
    }
```
This would solve the debounce and the cache issue. It might cause other problems, but I don't think it will.

**Comment by Joshpolansky** [comment]
Actually, i don't think it fixes the debounce, because there are 3 states
1. cache
2. machine.myvar <- are you saying update this?
3. plc data

**Comment by sclaiborne** [comment]
>Actually, i don't think it fixes the debounce, because there are 3 states

>    cache
>    machine.myvar <- are you saying update this?
>    plc data

Yes. So 
```js
change: function (event) {
    var $this = $(this);
    var localMachine = window[WEBHMI.getMachineName($this)];
    var variableName = WEBHMI.getVarName($this);
    var newValue = $this.val();
    localMachine.writeVariable(variableName, $this.val());
    localMachine[variableName] = newValue; // This line probably wont work but the concept is correct
    localMachine.readVariable(variableName); // Do we need to do this?
    $this.attr('data-machine-value-num', newValue) // I think we should do this
    }
```

**Comment by Joshpolansky** [comment]
Ya, I think I agree. We have stayed away from changing on the machine objective because we wanted it to reflect the known plc value but I think we might need to. 

I suppose after a write it is the best info about what should be there. 

And yes, I think we do want the read, because if we don't have it as a cyclic read then we won't update it otherwise

**Comment by sclaiborne** [comment]
>We have stayed away from changing on the machine object because we wanted it to reflect the known plc value but I think we might need to.
I suppose after a write it is the best info about what should be there.

I  agree that it is the best value. The only think I could maybe see is if you wait until the write is successful before writing to local machine value and updating the cached value. This is technically more correct but feels a little more tedious 

>And yes, I think we do want the read, because if we don't have it as a cyclic read then we won't update it otherwise

Good point. Unless we want to check if its a cyclic read but that feels unnecessary at this point.

**Review by sclaiborne — CHANGES_REQUESTED** [review]
Sounds like we agree based on the comments above what changes needed to be made.

**Review by sclaiborne — APPROVED** [review]

**Pull request merged**
